# Generated by Django 2.2 on 2021-11-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211118_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
