# Generated by Django 2.2 on 2021-11-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
