# Generated by Django 2.2 on 2021-12-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
